### ISSUE TITLE
High CPU Load (Reaching over 700%+)

### ISSUE THREAD

**Issue by SamGamerYT** [MCXboxBroadcast/Broadcaster#156] opened 2024-10-25 16:30 UTC
Geyser's Dump
https://dump.geysermc.org/geejpqy0UofIvu1G2x9B0LieNEObZmGr

"Startup Flags:"
java -Xms128M -Xmx10240M -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15 -Dvelocity.packet-decode-logging=true -jar velocity-436.jar

"Java Version:"
Java 21

"Proxy Jar:"
velocity-436

**Comment by SamGamerYT** [comment] 2024-10-25 16:31
![image](https://github.com/user-attachments/assets/1a956eb3-0ad1-4a42-aafd-60507f736527)

**Comment by SamGamerYT** [comment] 2024-10-25 16:31
Adding in Spark to generate a proper profiler, Will get back to you on the next network reboot.

**Comment by SamGamerYT** [comment] 2024-10-25 16:32
Version for MCXboxBroadcast: build 61 (git-master-08e0c3c)

**Comment by rtm516** [comment] 2024-10-25 16:39
Duplicate of #150 please add details to that thread

**Closed by rtm516** 2024-10-25 16:39 UTC
