### ISSUE TITLE
Latest Geyse/MC update breaks friends method. 

### ISSUE THREAD

**Issue by ChiefWarPig** [MCXboxBroadcast/Broadcaster#148] opened 2024-09-17 17:34 UTC
When players try to join since the 1.21.3 update earlier today they get the following message. Same device and account can log in via the server tab but obviously console arent able to log in that way. 
![Bedrock_Friends_Error](https://github.com/user-attachments/assets/634bb26e-8e91-4bff-9366-b5be44418593)

**Comment by ChiefWarPig** [comment] 2024-09-17 17:36
Console logs for reference. https://mclo.gs/KWC4vMu

**Comment by rtm516** [comment] 2024-09-17 18:37
Duplicate of #147

**Closed by rtm516** 2024-09-17 18:37 UTC
